language: java
branches:
  only:
    - master
    - /^release-v.*/
jdk:
  - oraclejdk7
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
script:
  - ./gradlew clean build test
after_success:
  - if [[ $TRAVIS_TAG =~ "^release-v[[:digit:]]+(\\.[[:digit:]]+)+$" ]] then ./gradlew bintrayUpload -PreleaseTag=$TRAVIS_TAG; fi;